Schools = new Mongo.Collection("schools");

if (Meteor.isServer) {
  if (Schools.find().count() < 50) {

    var list = ['3IL',
      '3WAcademy',
      'AGROCAMPUS OUEST',
      'AgroParisTech',
      'Agroparistech Grignon',
      'AgroSup Dijon',
      'AlumnEye',
      'AUDENCIA Nantes',
      'Autre',
      'Autre formation Ingénieurs',
      'Autre formation Management',
      'Autre université',
      'BBA EDHEC',
      'BTS',
      'CELSA',
      'CESI',
      'Chimie Lille ENSCL',
      'Chimie Montpellier ENSCM',
      'Chimie Nancy ENSIC',
      'Chimie ParisTech',
      'Conservatoire de Rouen',
      'CPE Lyon',
      'EBI',
      'EBS Paris',
      'ECAL',
      'ECAM EPMI',
      'ECAM Lyon',
      'ECAM Rennes',
      'ECAM Strasbourg',
      'ECE',
      "ECE Paris Ecole d'Ingénieurs",
      'ECEMA LYON',
      'Ecole Centrale Lille',
      'Ecole Centrale Lyon',
      'Ecole Centrale Marseille',
      'Ecole Centrale Nantes',
      'Ecole Centrale Paris',
      'Ecole de design Nantes Atlantique',
      "Ecole de l'air",
      "Ecole des Mines d'Albi Carmaux",
      "Ecole des Mines d'Alès",
      'Ecole des mines de Douai',
      'Ecole des Mines de Nancy',
      'Ecole des Mines de Nantes',
      'Ecole des Mines de Saint-Etienne',
      'Ecole des Mines ParisTech',
      'Ecole Polytechnique',
      "Ecole Supérieure d'Assurance",
      'ECPM',
      'ECS European Communication School',
      'ECTEI',
      'EDC Paris',
      'EDHEC Business School',
      'EEIGM',
      'EFAP',
      'EFFICOM',
      'EGC Avignon',
      'EGC de Tarbes',
      'EIDD',
      'EIGSI',
      'EISILV',
      'EISTI',
      'EIVP',
      'EM LYON',
      'EM Normandie',
      'EM Strasbourg',
      'EMLV',
      'EMP Groupe EDH',
      'ENAC',
      'ENASS',
      'ENIB',
      'ENIG',
      'ENIM',
      'ENIT',
      'ENPC Ecole des Ponts ParisTech',
      'ENS Cachan',
      'ENS Lyon',
      'ENS Ulm',
      'ENSAE ParisTech',
      'ENSAI',
      'ENSAIA',
      'ENSAM Arts et Métiers ParisTech',
      'ENSAT AGRO Toulouse',
      'ENSCBP',
      'ENSCCF',
      'ENSE3 Grenoble INP',
      'ENSEA',
      'ENSEEIHT',
      'ENSEIRB',
      'ENSEM',
      'ENSG',
      'ENSGSI',
      'ENSGTI',
      'ENSIACET',
      'ENSIAME',
      'ENSIB',
      'ENSIBS',
      'ENSICAEN',
      'ENSIIE',
      'ENSIL',
      'ENSIMAG Grenoble INP',
      'ENSIP',
      'ENSMA',
      'ENSMM',
      'ENSPM Pétrole et moteurs',
      'ENSPS',
      'ENSTA Bretagne',
      'ENSTA ParisTech',
      'ENTPE',
      'EOST',
      "EPF Ecole d'Ingénieurs",
      'EPITA',
      'EPITECH',
      'EPMI',
      'EPSCI Groupe ESSEC',
      'ESADHAR',
      'ESAM',
      'ESC Amiens Picardie',
      'ESC Brest',
      'ESC Clermont',
      'ESC Dijon Bourgogne',
      'ESC Rennes',
      'ESC Saint-Etienne',
      'ESCE',
      'ESCEM',
      'ESCG Paris',
      'ESCI',
      'ESCIP',
      'ESCOM',
      'ESCP Europe',
      'ESCT Toulon',
      'ESDES',
      'ESDHEM',
      'ESEO',
      'ESG Management School',
      'ESGCI',
      'ESGF',
      'ESGI',
      'ESI Reims',
      'ESIAME',
      'ESIEE',
      'ESIEE Amiens',
      'ESIEE Management',
      'ESIGELEC',
      'ESIGETEL',
      'ESIL',
      'ESILV',
      'ESIREM Dijon',
      'ESISAR Grenoble INP',
      'ESLSCA',
      'ESM Saint-Cyr',
      'ESM-A',
      'ESME Sudria',
      'ESMISAB',
      'ESPCI ParisTech',
      'ESPRIT',
      'ESSCA Angers',
      'ESSEC  Business School',
      'ESSTIN',
      'ESTACA',
      'ESTACOM',
      'ESTIA',
      'ESTICE',
      'ESTICE - ESPAS',
      'ESTP',
      'ESUP',
      'EU Business School',
      'EURECOM',
      'FBS (France Business School)',
      'Formation hors France',
      'Forum Atlantique',
      'Génie Industriel Grenoble INP',
      'Georgia Tech Lorraine',
      'Grenoble Ecole de management / ESC Grenoble',
      'Groupe EFREI',
      'Groupe ESA',
      'Groupe ESC Pau',
      'Groupe ESC Troyes',
      'Groupe ESIEA',
      'Groupe Sup de Co La Rochelle',
      'HEC Montréal',
      'HEC Paris',
      'HEI',
      'IAE Aix en Provence',
      'IAE Bordeaux',
      'IAE Caen',
      'IAE de Bretagne Occidentale',
      'IAE Dijon',
      'IAE France',
      'IAE Grenoble',
      'IAE Gustave Eiffel Paris Est',
      'IAE La Réunion',
      'IAE Lille',
      'IAE Lyon',
      'IAE Montpellier',
      'IAE Nancy',
      'IAE Nantes',
      'IAE Nice',
      'IAE Paris Sorbonne',
      'IAE Poitiers',
      'IAE Rennes (IGR)',
      'IAE Rouen',
      'IAE Toulouse',
      'IAE Tours',
      'IAE Valenciennes',
      'ICAM',
      'ICD',
      'ICN Business School',
      'IDRAC',
      'IEP Sciences Po Aix',
      'IEP Sciences Po Bordeaux',
      'IEP Sciences Po Grenoble',
      'IEP Sciences Po Lille',
      'IEP Sciences Po Lyon',
      'IEP Sciences Po Paris',
      'IEP Sciences Po Rennes',
      'IEP Sciences Po Strasbourg',
      'IEP Sciences Po Toulouse',
      'IESEG',
      'IFAG',
      'IFI (RBS)',
      'IFMA',
      'IFSAC (ESC Pau)',
      'IFSECC',
      'IGS',
      'IMMD',
      'INFOSUP',
      'Ingénieurs 2000',
      'INSA Lyon',
      'INSA Rennes',
      'INSA Rouen',
      'INSA Strasbourg',
      'INSA Toulouse',
      'INSEEC Business School',
      'INSEEC MSc & MBA',
      'Institut Catholique de Paris.',
      "Institut d'Optique Graduate School",
      'Institut de Gestion Sociale (IGS)',
      'INSTN',
      'IONIS STM',
      'IPAG',
      'IPSA',
      'IRCOM',
      'ISA Lille',
      'ISAE',
      'ISARA Lyon',
      'ISC Paris',
      'ISCID',
      'ISCOM',
      'ISEADD',
      'ISEE',
      'ISEG Business & Finance School',
      'ISEG Marketing & Communication School',
      'ISEM',
      'ISEN Brest',
      'ISEN Lille',
      'ISEN Toulon',
      'ISEP',
      'ISG',
      'ISGP',
      'ISITV',
      'ISNAB',
      'ISTDI',
      'ISTEC Paris',
      'ISTIL',
      'ISTY',
      'IT Paris Eiffel',
      'ITECH',
      'ITEEM',
      'ITIC',
      'ITIN',
      'IUT',
      'IUT du Limousin',
      'IUT Lyon I Génie civil',
      'IUT Tarbes',
      'Junior-Entreprises',
      'KEDGE Business School',
      'LaSalle Beauvais Institut Polytechnique',
      'Le CNAM',
      'Lycée',
      'MATMECA',
      'MBA ESG',
      'Montpellier Business School',
      'Montpellier Supagro',
      "Muséum national d'Histoire naturelle",
      'NEOMA Business School',
      'Novancia Business School',
      'ONIRIS',
      'PAGORA Grenoble INP',
      'Paris School of Business',
      'PHELMA Grenoble INP',
      'PIGIER',
      'Pôle Universitaire Léonard de Vinci',
      "Polytech' Clermont-Ferrand",
      "Polytech' Grenoble",
      "Polytech' Lille",
      "Polytech' Marseille",
      "Polytech' Montpellier",
      "Polytech' Nantes",
      "Polytech' Nice Sophia Antipolis",
      "Polytech' Orléans",
      "Polytech' Paris",
      "Polytech' Paris Sud",
      "Polytech' Tours",
      'PPA',
      'Prépa',
      'SciencesCom (Audencia)',
      'SKEMA Business School',
      'Sup de Pub',
      'Sup de V',
      'Sup des RH',
      'Supélec',
      'SUPINFO',
      'SUPMECA',
      'TECOMAH',
      'TELECOM Bretagne',
      'TELECOM Ecole de management',
      'TELECOM Lille 1',
      'TELECOM Nancy',
      'TELECOM ParisTech',
      'Télécom Physique Strasbourg',
      'TELECOM Saint-Etienne',
      'TELECOM SudParis',
      'Toulouse Business School',
      'Université Blaise Pascal Clermont 2',
      'Université Bordeaux 1',
      'Université Bordeaux 2 Victor Segalen',
      'Université Bordeaux 3 Michel de Montaigne',
      'Université Bordeaux 4 Montesquieu',
      "Université Catholique de L'Ouest (UCOBS)",
      'Université Catholique de Lille',
      'Université Catholique de Lyon (UCLy)',
      'Université Claude Bernard Lyon 1',
      "Université d'Angers",
      "Université d'Artois",
      "Université d'Auvergne Clermont 1",
      "Université d'Avignon et des Pays de Vaucluse",
      "Université d'Orléans",
      'Université de Bourgogne Dijon',
      'Université de Bretagne Occidentale (UBO)',
      'Université de Bretagne Occidentale Brest',
      'Université de Bretagne-Sud',
      'Université de Caen Basse-Normandie',
      'Université de Cergy-Pontoise',
      'Université de Corse Pascal Paoli',
      'Université de Franche-Comté Besançon',
      'Université de la Méditerranée Aix-Marseille 2',
      'Université de la Réunion',
      'Université de La Rochelle',
      'Université de Limoges',
      'Université de Mulhouse Haute-Alsace (UHA)',
      'Université de Nantes',
      'Université de Nice Sofia-Antipolis',
      'Université de Nîmes (UNIMES)',
      "Université de Pau et des Pays de l'Adour",
      'Université de Perpignan Via Domitia (UPVD)',
      'Université de Picardie Jules Verne (UPJV)',
      'Université de Poitiers',
      'Université de Provence Aix-Marseille 1',
      'Université de Reims Champagne-Ardenne',
      'Université de Rouen',
      'Université de Savoie',
      'Université de Strasbourg',
      'Université de Toulouse',
      'Université de Valenciennes',
      'Université de Versailles Saint-Quentin-en-Yvelines (UVSQ)',
      'Université des Antilles et de la Guyane',
      'Université du Havre',
      "Université du Littoral Côte d'Opale (UCLO)",
      'Université du Maine',
      'Université du Sud Toulon Var',
      "Université Evry Val d'Essonne",
      'Université Jean Moulin Lyon 3',
      'Université Joseph Fourier Grenoble 1',
      'Université Lille 1',
      'Université Lille 2',
      'Université Lille 3',
      'Université Lumière Lyon 2 (UL2)',
      'Université Montpellier 1',
      'Université Montpellier 2',
      'Université Nancy 1 Henri Poincaré',
      'Université Nancy 2',
      'Université Paris 1 Panthéon-Sorbonne',
      'Université Paris 13',
      'Université Paris 2 Panthéon-Assas',
      'Université Paris 3 Sorbonne Nouvelle',
      'Université Paris 4 Paris-Sorbonne',
      'Université Paris 6 Pierre et Marie Curie (UPMC)',
      'Université Paris 8 Vincennes-Saint-Denis',
      'Université Paris Dauphine',
      'Université Paris Descartes 5',
      'Université Paris Diderot 7',
      'Université Paris Est Créteil (UPEC Paris 12)',
      'Université Paris Ouest  Nanterre Paris 10',
      'Université Paris-Est Marne-la-Vallée',
      'Université Paris-Nord 13',
      'Université Paris-Sud 11',
      'Université Paul Cézanne Aix-Marseille 3',
      'Université Paul Verlaine Metz',
      'Université Paul-Valéry Montpellier 3',
      'Université Pierre-Mendès-France Grenoble 2 (UPMF)',
      'Université Rennes 1',
      'Université Rennes 2',
      'Université Saint-Etienne Jean Monnet',
      'Université Stendhal Grenoble 3',
      'Université Toulouse 1 Capitole',
      'Université Toulouse 2 Le Mirail',
      'Université Toulouse 3 Paul Sabatier',
      'Université Tours François Rabelais',
      'UTBM',
      'UTC',
      'UTT'];
    var spes = [
      "Image (IMA)",
      "Modélisation aléatoire et Calcul scientifique (MACS)",
      "Systèmes et logiciels répartis (SLR)",
      "Systèmes et objets de communications (SOCOM)",
      "Sécurité des réseaux et infrastructures informatiques (SR2I)",
      "Interaction Homme-Machine et Informatique Graphique 3D (IGR)",
      "Mathématiques, Informatique théorique et Recherche opérationnelle (MITRO)",
      "Réseaux (RES)",
      "Signal et données numériques : modèles et applications (SIGMA)",
      "Stratégie, innovation, marchés (SIM)",
      "Algèbre, codage, crypto, quantique (ACCQ)",
      "Sciences des données (SD)",
      "Systèmes embarqués (SE)",
    ];
    Schools.remove({});
    list.forEach(function (elem) {
      Schools.insert({
        name: elem,
        specialities: spes
      });
    });
  }
}